SimpleDMS/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('dms/', include('dms.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dms/urls.py
from django.urls import path

from .views import department

app_name = 'dms'
urlpatterns = [
    # /dms/
    path('', department.index, name='index'),
    #
    path('<int:department_id>/', department.details, name='department_details_path'),
]

dms/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(verbose_name='Kategoria', max_length=50)
    description = models.TextField('Opis', max_length=500)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Kategoria'
        verbose_name_plural = 'Kategorie'



class Department(models.Model):
    '''Department of the factory'''
    name = models.CharField(verbose_name='Nazwa działu', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Dział"
        verbose_name_plural = 'Działy'


class Product(models.Model):
    '''Product'''
    name = models.CharField(verbose_name='Nazwa produktu', max_length=150)
    customer_number = models.IntegerField(verbose_name='Numer produktu')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Produkt'
        verbose_name_plural = 'Produkty'


class Document(models.Model):
    '''Published document'''
    title = models.CharField(verbose_name='Tytuł dokumentu', max_length=300)
    document_number = models.CharField(verbose_name="Numer dokumentu/procedury", max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Kategoria')
    product = models.ManyToManyField(Product, verbose_name='Produkty', blank=True)
    department = models.ManyToManyField(Department, verbose_name="Działy", blank=True)
    document_file = models.FileField(verbose_name="Plik dokumentu")

    def __str__(self):
        return f"{self.document_number} - {self.title}"

    class Meta:
        verbose_name = 'Dokument'
        verbose_name_plural = 'Dokumenty'



class Formular(models.Model):
    name = models.CharField(verbose_name="Tytuł formularza", max_length=150)
    #file_url = models.CharField(verbose_name="Adres pliku")
    test = models.FilePathField(path='/Users/tgaladyk/Documents/ML/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Formularz'
        verbose_name_plural = "Formularze"

dms/views/department.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from dms.models import Department



# Create your views here.

def index(request):
    departments_list = Department.objects.all()
    context = { 'departments_list' : departments_list}

    return render(request, 'dms/index.html', context)


def details(request, department_id):
    department = get_object_or_404(Department, pk=department_id)
    return render(request, 'dms/department_details.html', {'department': department})

dms/views/index.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from dms.models import Department



# Create your views here.

def index(request):
    departments_list = Department.objects.all()
    context = { 'departments_list' : departments_list}

    return render(request, 'dms/index.html', context)

dms/templates/dms/department_details.html
{% extends "layout.html" %}

{% block content %}
    {{ department }}
{% endblock content %}

dms/templates/dms/index.html
{% extends "layout.html" %}


{% block content %}
{% if departments_list %}
<!-- <div class="card-deck mb-3">-->
<div class="row">
    {% for department in departments_list %}
            <div class="col-sm-xs mx-3">
            <div class="card border-dark my-1 bg-light" style="width: 20rem;">
                <div class="card-body">
                <h5 class="card-title">{{ department.name }}</h5>
                <p class="card-text">Wybierz dział by wyszukać dokumentację.</p>
                <a href="{% url 'dms:department_details_path' department.id %}" class="btn btn-secondary">Szukaj dokumentacji</a>
              </div>
            </div>
            </div>

    {% endfor %}
</div>
{% else %}
    <p>Brak działów do wyświetlenia</p>
{% endif %}
{% endblock content %}

dms/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SimpleDMS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'dms:index' %}">SimpleDMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
</div>


<div class="content container">

    {% block content %}

    {% endblock content %}

</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>